print("Name: Bataller, Christian")
print("Birthday: March 12, 2004")
print("Gender: Male")
print("Email: christianbataller788@gmail.com")

print("Welcome to the team! - Christian")
print("Hello team! - Steven")
print("Hello team! - Gwen")
print("Welcome to the team! - Sar")
print ("Change")
print("Welcome to the team! - Gwenn!") print("Welcome to the team! - Gwenn!") 